bot:
  prefix: "!"
  token: !ENV "BOT_TOKEN"
  description: "A minimal general purpose bot for Chill Corner discord server"

channels:
  staff_room: 711567984686137426

roles:
  mod: 445407188375306243
  verified: 480030345916317746
  artist: 525019822728282113

keys:
  openai_key: !ENV "OPENAI_KEY"

config:
  required_keys: ["bot.token"]
